### ISSUE TITLE
xray-rails fails to initialize after upgrading to sprockets-rails 3.0.0

### ISSUE THREAD

**Issue by mattbrictson** [brentd/xray-rails#61]
The 3.0.0 version of sprockets-rails was just released. Unfortunately, as I write this there is no changelog or release notes, so it is hard to say exactly what is different. However, a Rails 4.2.5 app with sprockets-rails 3.0.0 and xray-rails now fails to load:

```
xray-rails requires the Rails asset pipeline.
The asset pipeline is currently disabled in this application.
Either convert your application to use the asset pipeline, or remove xray-rails from your Gemfile.
xray-rails-0.1.17/lib/xray/engine.rb:10:in `block in <class:Engine>
```

**Comment by sunsations** [comment]
+1

**Comment by sfcgeorge** [comment]
Yeah same problem. Strange that Rails hasn't locked down the version of `sprockets-rails` I wonder if v3 is even intended to be used with Rails 4.2, the lack of changelog really doesn't help. 

The issue seems to be where assets is initialized as this line now fails https://github.com/brentd/xray-rails/blob/master/lib/xray/engine.rb#L100

**Comment by mattbrictson** [comment]
@sunsations @sfcgeorge Can you try my branch referenced in PR #62 ? It should fix this problem.

**Comment by sunsations** [comment]
@mattbrictson  It fixes the problem :+1: Thank you.
